consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
update:
  function: update/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    ENTRA_CLIENT_ID: $ENTRA_CLIENT_ID
    ENTRA_CLIENT_SECRET: $ENTRA_CLIENT_SECRET
    ENTRA_OAUTH_REDIRECT_URI: $ENTRA_OAUTH_REDIRECT_URI
    ENTRA_TENENT_ID: $ENTRA_TENENT_ID
    ENTRA_TOKEN_ENDPOINT: $ENTRA_TOKEN_ENDPOINT
    ENTRA_AUTH_SCOPE: $ENTRA_AUTH_SCOPE
    ENTRA_AUTH_GRANT_TYPE: $ENTRA_AUTH_GRANT_TYPE
    ENTRA_SITE_ID: $ENTRA_SITE_ID
    MICROSOFT_GRAPH_BASE_URL: $MICROSOFT_GRAPH_BASE_URL
    SHAREPOINT_DIRECTORY_PATH_FROM_ROOT: $SHAREPOINT_DIRECTORY_PATH_FROM_ROOT
  annotations:
    require-adobe-auth: true
    final: true
delete:
  function: delete/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
