consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: false
    final: true
update:
  function: update/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    ENTRA_CLIENT_ID: $ENTRA_CLIENT_ID
    ENTRA_CLIENT_SECRET: $ENTRA_CLIENT_SECRET
    ENTRA_OAUTH_REDIRECT_URI: $ENTRA_OAUTH_REDIRECT_URI
    ENTRA_TENANT_ID: $ENTRA_TENANT_ID
    ENTRA_TOKEN_ENDPOINT: $ENTRA_TOKEN_ENDPOINT
    ENTRA_AUTH_SCOPE: $ENTRA_AUTH_SCOPE
    ENTRA_AUTH_GRANT_TYPE: $ENTRA_AUTH_GRANT_TYPE
    MICROSOFT_GRAPH_BASE_URL: $MICROSOFT_GRAPH_BASE_URL
    SHAREPOINT_DIRECTORY_PATH_FROM_ROOT: $SHAREPOINT_DIRECTORY_PATH_FROM_ROOT
    FILE_NAME_TO_READ: $FILE_NAME_TO_READ
  annotations:
    require-adobe-auth: false
    final: true
delete:
  function: delete/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    LOG_LEVEL: debug
    ENTRA_CLIENT_ID: $ENTRA_CLIENT_ID
    ENTRA_CLIENT_SECRET: $ENTRA_CLIENT_SECRET
    ENTRA_OAUTH_REDIRECT_URI: $ENTRA_OAUTH_REDIRECT_URI
    ENTRA_TENANT_ID: $ENTRA_TENANT_ID
    ENTRA_TOKEN_ENDPOINT: $ENTRA_TOKEN_ENDPOINT
    ENTRA_AUTH_SCOPE: $ENTRA_AUTH_SCOPE
    ENTRA_AUTH_GRANT_TYPE: $ENTRA_AUTH_GRANT_TYPE
    MICROSOFT_GRAPH_BASE_URL: $MICROSOFT_GRAPH_BASE_URL
    SHAREPOINT_DIRECTORY_PATH_FROM_ROOT: $SHAREPOINT_DIRECTORY_PATH_FROM_ROOT
    SHAREPOINT_HOST_NAME: $SHAREPOINT_HOST_NAME
    FILE_NAME_TO_READ: $FILE_NAME_TO_READ
  annotations:
    require-adobe-auth: false
    final: true
