application:
  runtimeManifest:
    packages:
      ingestion:
        license: Apache-2.0
        actions:
          $include: ./actions/ingestion/actions.config.yaml
      product-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/product/commerce/actions.config.yaml
      product-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/product/external/actions.config.yaml
      customer-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/customer/commerce/actions.config.yaml
      customer-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/customer/external/actions.config.yaml
      customer-group-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/customer-group/commerce/actions.config.yaml
      customer-group-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/customer-group/external/actions.config.yaml
