application:
  runtimeManifest:
    packages:
      starter-kit:
        license: Apache-2.0
        actions:
          # Please DO NOT DELETE this action; future functionalities planned for upcoming starter kit releases may stop working.
          info:
            function: actions/starter-kit-info/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
      product-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/product/commerce/actions.config.yaml
      #product-backoffice:
      #  license: Apache-2.0
      #  actions:
      #    $include: ./actions/product/external/actions.config.yaml
productDependencies:
  - code: COMMC
    minVersion: 2.4.4
