application:
  runtimeManifest:
    packages:
      starter-kit:
        license: Apache-2.0
        actions:
          info:
            function: actions/starter-kit-info/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
      sale-rule-content-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/sale-rule-content/commerce/actions.config.yaml
productDependencies:
  - code: COMMC
    minVersion: 2.4.5