commerce-consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commerce-created:
  function: created/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commerce-updated:
  function: updated/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commerce-deleted:
  function: deleted/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
