commercececonsumer:
  function: commerce/consumer/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commercecreated:
  function: commerce/created/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commerceupdated:
  function: commerce/created/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
commercedeleted:
  function: commerce/deleted/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
