consumer:
  function: consumer/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
updated:
  function: updated/index.js
  web: 'no'
  runtime: nodejs:16
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
